version: 2

models:

  # =========================
  # PROJECTS
  # =========================
  - name: stg_projects
    description: "Projets immobiliers – historisation SCD2"
    columns:
      - name: project_identifier
        tests:
          - not_null

      - name: entity_identifier
        tests:
          - not_null

      - name: project_name
        tests:
          - not_null

      - name: event_timestamp
        tests:
          - not_null

      - name: phase
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - project_identifier
            - entity_identifier
            - valid_from


  # =========================
  # ADDRESS
  # =========================
  - name: stg_address
    description: "Adresse des projets – historisation SCD2"
    columns:
      - name: project_identifier
        tests:
          - not_null

      - name: entity_identifier
        tests:
          - not_null

      - name: event_timestamp
        tests:
          - not_null

      - name: valid_from
        tests:
          - not_null

      - name: is_current
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - project_identifier
            - entity_identifier
            - valid_from

  # =========================
  # INVESTORS
  # =========================
  - name: stg_investors
    description: "Investisseurs par projet – SCD2"
    columns:
      - name: project_identifier
        tests:
          - not_null

      - name: entity_identifier
        tests:
          - not_null

      - name: is_active
        tests:
          - not_null

      - name: valid_from
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - project_identifier
            - entity_identifier
            - investor_identifier
            - valid_from


